SELECT ID,
CASE   
    WHEN PER='4' THEN 'LOW'
    WHEN PER='3' THEN 'MEDIUM'
    WHEN PER='2' THEN 'HIGH'
    WHEN PER='1' THEN 'CRITICAL'
END AS COLONY_NAME
FROM(SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER FROM ECOLI_DATA) AS F
ORDER BY ID ASC