-- 코드를 작성해주세요
SELECT ID,	EMAIL,	FIRST_NAME,	LAST_NAME
FROM DEVELOPERS D JOIN SKILLCODES S ON S.CODE&SKILL_CODE
WHERE EXISTS SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE CATEGORY='Front End') 
ORDER BY ID ASC