-- 코드를 작성해주세요 부모 제노타입 & 자기 제노타입 해서 
SELECT A.ID, A.GENOTYPE, E.GENOTYPE AS PARENT_GEONTYPE
FROM ECOLI_DATA E JOIN ECOLI_DATA A ON E.ID=A.PARENT_ID
WHERE E.GENOTYPE=(A.GENOTYPE & E.GENOTYPE)
ORDER BY A.ID ASC