-- 코드를 작성해주세요
SELECT *,D.YEAR,  (D.M-E.SIZE_OF_COLONY) AS YEAR_DEV,	E.ID
FROM ECOLI_DATA E JOIN (
SELECT DIFFERENTIATION_DATE, YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS M
FROM ECOLI_DATA
GROUP BY YEAR
) D ON  E.DIFFERENTIATION_DATE=D.DIFFERENTIATION_DATE
ORDER BY D.YEAR ASC,  YEAR_DEV ASC