-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY A ON C.CAR_ID=A.CAR_ID
WHERE C.CAR_TYPE='세단'
AND A.START_DATE LIKE "2022-10%"
ORDER BY C.CAR_ID DESC;