-- 코드를 작성해주세요
SELECT QUARTER, COUNT(QUARTER)
FROM ECOLI_DATA D
JOIN (
SELECT 
CASE
    WHEN MONTH(DIFFERENTIATION_DATE)>=10 THEN '4Q'
    WHEN MONTH(DIFFERENTIATION_DATE)>=7 THEN '3Q'
    WHEN MONTH(DIFFERENTIATION_DATE)>=4 THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE)>=1 THEN '1Q'
END AS QUARTER, ID
FROM ECOLI_DATA
) E ON D.ID=E.ID
GROUP BY QUARTER
ORDER BY QUARTER ASC